a= input("Digite um número: ")
b= input("Agora digite outro número: ")
soma=int (a)+int (b)
divisão=int (a)/int (b)
multiplicação=int (a)*int (b)
subtração=int (a)-int (b)
print("essa é a soma:",soma)
print("essa é a subtração:",subtração)
print("essa é a mustiplição:",multiplicação)
print("essa é a divisão:",divisão)
